### ISSUE TITLE
Demo case throw an error.

### ISSUE THREAD

**Issue by weizhiting** [aaronwtr/PertEval#37]
When running the demo case, the config in train.py  need a target, i.e., `cfg.data._target_`   (line 62 in train.py).   but the mlp_norman_train.yaml does not define a target. 

How can i fix this.  hope to receive your reply.

**Comment by weizhiting** [comment]
..

**Comment by aaronwtr** [comment]
Hi @weizhiting, I cannot reproduce this without more information. 

Here is some general information. While `mlp_norman_train.yaml` does not explicitly provide a target for the datamodule, the target should definitely be passed to Hydra as the `train.yaml` which get called for `train.py` points the default data file correctly to `configs/data/perturb.yaml`. `perturb.yaml` does contain the correct target. Could you verify all the config files are properly located locally?

**Comment by weizhiting** [comment]
Sorry for the delay response.

This error occurred because I hadn’t installed a dependency package. After installing this package, the demo ran successfully.  Thank you once again for your work.

**Comment by aaronwtr** [comment]
Hi @weizhiting, 

Thank you for the clarification! Was this package missing from our requirements file? If so, could you please point us to which package was missing so that we can include it. Thank you for using PertEval!

**Comment by weizhiting** [comment]
Hi, @aaronwtr  no package was missed in the requirement file. 
Additionally, I have another question and open another issue.
Thx.
